# COB Pend Resolution Pipeline - Agent definitions
# Each agent handles one stage of the 8-stage resolution pipeline.
#
# Stage 1: AI Summary (generated by orchestrator)
# Stage 2: Hold Code Validation (hold_code_agent)
# Stage 3: Member Eligibility & COB History (eligibility_agent)
# Stage 4: Timely Filing Check (timely_filing_agent)
# Stage 5: Coordination Rule Application (coordination_agent)
# Stage 6: COB Calculation (cob_calculation_agent)
# Stage 7: Posting Recommendation (posting_agent)
# Stage 8: Post Validation & QA (post_validation_agent)

from app.agents.orchestrator import run_orchestrator
from app.agents.base_agent import call_bedrock, store_stage_output
